# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10hello_grpc.proto\"\x19\n\x08MyNumber\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x31\n\tMyService\x12$\n\nMyFunction\x12\t.MyNumber\x1a\t.MyNumber\"\x00\x62\x06proto3'
)




_MYNUMBER = _descriptor.Descriptor(
  name='MyNumber',
  full_name='MyNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='MyNumber.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=45,
)

DESCRIPTOR.message_types_by_name['MyNumber'] = _MYNUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyNumber = _reflection.GeneratedProtocolMessageType('MyNumber', (_message.Message,), {
  'DESCRIPTOR' : _MYNUMBER,
  '__module__' : 'hello_grpc_pb2'
  # @@protoc_insertion_point(class_scope:MyNumber)
  })
_sym_db.RegisterMessage(MyNumber)



_MYSERVICE = _descriptor.ServiceDescriptor(
  name='MyService',
  full_name='MyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=47,
  serialized_end=96,
  methods=[
  _descriptor.MethodDescriptor(
    name='MyFunction',
    full_name='MyService.MyFunction',
    index=0,
    containing_service=None,
    input_type=_MYNUMBER,
    output_type=_MYNUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYSERVICE)

DESCRIPTOR.services_by_name['MyService'] = _MYSERVICE

# @@protoc_insertion_point(module_scope)
